/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import Admin.Add_1;
import Admin.AdminDashboard;
import Config.config;
import Config.session;
import Main.LandingPage;
import Main.LoginPage;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sheena
 */
public class LogEnergy extends javax.swing.JFrame {

    /**
     * Creates new form LogEnergy
     */
    session sess = session.getInstance();
    public LogEnergy() {
        if (session.isInstanceEmpty() || sess.getUserId() == 0) 
        {
        JOptionPane.showMessageDialog(null, "Login Required!");
        new LoginPage().setVisible(true);
        dispose();
        return;
        }
        initComponents();
        DisplayLog();
        loadStatistics();
    }
    
    void DisplayLog(){

    config con = new config();
    
    String sql = "SELECT logs_id, task, energy_level, date "
               + "FROM energy_log WHERE u_id = " + sess.getUserId();

    con.displayData(sql, logTable);
}
    
    void loadStatistics() {

    config con = new config();

    String sql = "SELECT AVG(energy_level) AS avg_energy, "
               + "MIN(energy_level) AS min_energy, "
               + "MAX(energy_level) AS max_energy "
               + "FROM energy_log WHERE u_id = " + sess.getUserId();

    try (Connection conn = config.connectDB();
         Statement stmt = conn.createStatement();
         ResultSet rs = stmt.executeQuery(sql)) {

        if (rs.next()) {
            avgValue.setText(String.format("%.2f", rs.getDouble("avg_energy")));
            lowestValue.setText(String.valueOf(rs.getInt("min_energy")));
            highestValue.setText(String.valueOf(rs.getInt("max_energy")));
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        Add = new javax.swing.JPanel();
        AddLbl = new javax.swing.JLabel();
        Ud = new javax.swing.JPanel();
        UpdateLbl = new javax.swing.JLabel();
        Delete = new javax.swing.JPanel();
        DeleteLbl = new javax.swing.JLabel();
        SearchText = new javax.swing.JTextField();
        Search = new javax.swing.JPanel();
        SearchLbl = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        avgValue = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        highestValue = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lowestValue = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        logTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        Home = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        App = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Mentors = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Acc = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Logout = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 737));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(1300, 737));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        Logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoMouseClicked(evt);
            }
        });
        jPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 30, 290, 110));

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("LOG ENERGY");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Broadway", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EnergiFy");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 180, 30));

        jScrollPane1.setBackground(new java.awt.Color(0, 102, 102));

        jPanel2.setBackground(new java.awt.Color(16, 79, 79));
        jPanel2.setMaximumSize(new java.awt.Dimension(1300, 737));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Add.setBackground(new java.awt.Color(0, 51, 51));
        Add.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddMouseExited(evt);
            }
        });
        Add.setLayout(null);

        AddLbl.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        AddLbl.setForeground(new java.awt.Color(255, 255, 255));
        AddLbl.setText("ADD");
        Add.add(AddLbl);
        AddLbl.setBounds(44, 16, 41, 22);

        jPanel2.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 50));

        Ud.setBackground(new java.awt.Color(0, 51, 51));
        Ud.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Ud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UdMouseExited(evt);
            }
        });
        Ud.setLayout(null);

        UpdateLbl.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        UpdateLbl.setForeground(new java.awt.Color(255, 255, 255));
        UpdateLbl.setText("UPDATE");
        Ud.add(UpdateLbl);
        UpdateLbl.setBounds(27, 16, 79, 22);

        jPanel2.add(Ud, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 130, 50));

        Delete.setBackground(new java.awt.Color(0, 51, 51));
        Delete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeleteMouseExited(evt);
            }
        });
        Delete.setLayout(null);

        DeleteLbl.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        DeleteLbl.setForeground(new java.awt.Color(255, 255, 255));
        DeleteLbl.setText("DELETE");
        Delete.add(DeleteLbl);
        DeleteLbl.setBounds(24, 16, 81, 22);

        jPanel2.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 130, 50));

        SearchText.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.lightGray));
        SearchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTextActionPerformed(evt);
            }
        });
        SearchText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SearchTextKeyTyped(evt);
            }
        });
        jPanel2.add(SearchText, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 300, 50));

        Search.setBackground(new java.awt.Color(0, 51, 51));
        Search.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SearchMouseExited(evt);
            }
        });
        Search.setLayout(null);

        SearchLbl.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        SearchLbl.setForeground(new java.awt.Color(255, 255, 255));
        SearchLbl.setText("SEARCH");
        Search.add(SearchLbl);
        SearchLbl.setBounds(25, 16, 81, 22);

        jPanel2.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 130, 50));

        jPanel3.setBackground(new java.awt.Color(16, 79, 79));
        jPanel3.setLayout(null);

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, null));
        jPanel4.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabel13.setText("Average Energy");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(10, 10, 140, 22);

        avgValue.setFont(new java.awt.Font("Bookman Old Style", 0, 36)); // NOI18N
        jPanel4.add(avgValue);
        avgValue.setBounds(10, 40, 140, 70);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (13).png"))); // NOI18N
        jPanel4.add(jLabel11);
        jLabel11.setBounds(0, 0, 250, 120);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(30, 30, 250, 120);

        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, null));
        jPanel6.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabel15.setText("Highest Energy Level");
        jPanel6.add(jLabel15);
        jLabel15.setBounds(10, 10, 200, 20);

        highestValue.setFont(new java.awt.Font("Bookman Old Style", 0, 36)); // NOI18N
        jPanel6.add(highestValue);
        highestValue.setBounds(10, 40, 70, 70);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (13).png"))); // NOI18N
        jPanel6.add(jLabel12);
        jLabel12.setBounds(0, 0, 250, 120);

        jPanel3.add(jPanel6);
        jPanel6.setBounds(610, 30, 250, 120);

        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, null));
        jPanel7.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabel14.setText("Lowest Energy Level");
        jPanel7.add(jLabel14);
        jLabel14.setBounds(10, 10, 190, 22);

        lowestValue.setFont(new java.awt.Font("Bookman Old Style", 0, 36)); // NOI18N
        jPanel7.add(lowestValue);
        lowestValue.setBounds(10, 40, 70, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (13).png"))); // NOI18N
        jPanel7.add(jLabel2);
        jLabel2.setBounds(0, 0, 250, 120);

        jPanel3.add(jPanel7);
        jPanel7.setBounds(320, 30, 250, 120);

        logTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(logTable);

        jPanel3.add(jScrollPane4);
        jScrollPane4.setBounds(30, 180, 840, 480);

        jScrollPane3.setViewportView(jPanel3);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 900, 460));

        jScrollPane1.setViewportView(jPanel2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 940, 570));

        jLabel10.setBackground(new java.awt.Color(0, 153, 153));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, -1));

        Home.setBackground(new java.awt.Color(0, 51, 51));
        Home.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeMouseExited(evt);
            }
        });
        Home.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("HOME");
        Home.add(jLabel6);
        jLabel6.setBounds(139, 16, 79, 29);

        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 360, 60));

        App.setBackground(new java.awt.Color(16, 79, 79));
        App.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        App.setForeground(new java.awt.Color(255, 255, 255));
        App.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        App.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AppMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AppMouseExited(evt);
            }
        });
        App.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LOG ENERGY");
        App.add(jLabel3);
        jLabel3.setBounds(100, 20, 168, 29);

        jPanel1.add(App, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 360, 60));

        Mentors.setBackground(new java.awt.Color(0, 51, 51));
        Mentors.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Mentors.setForeground(new java.awt.Color(255, 255, 255));
        Mentors.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Mentors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MentorsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MentorsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MentorsMouseExited(evt);
            }
        });
        Mentors.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MENTOR");
        Mentors.add(jLabel5);
        jLabel5.setBounds(120, 20, 113, 20);

        jPanel1.add(Mentors, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 360, 60));

        Acc.setBackground(new java.awt.Color(0, 51, 51));
        Acc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Acc.setForeground(new java.awt.Color(255, 255, 255));
        Acc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Acc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AccMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AccMouseExited(evt);
            }
        });
        Acc.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ACCOUNT");
        Acc.add(jLabel7);
        jLabel7.setBounds(120, 20, 125, 20);

        jPanel1.add(Acc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 360, 60));

        Logout.setBackground(new java.awt.Color(0, 51, 51));
        Logout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutMouseExited(evt);
            }
        });
        Logout.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("LOGOUT");
        Logout.add(jLabel8);
        jLabel8.setBounds(126, 16, 107, 29);

        jPanel1.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 360, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoMouseClicked
        LandingPage Logo = new LandingPage();
        Logo.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoMouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        UserDashboard Users = new UserDashboard();
        Users.setVisible(true);
        dispose();
    }//GEN-LAST:event_HomeMouseClicked
     public void setColor(JPanel p){
        p.setBackground(new Color(0,51,51));
    }
    public void resetColor(JPanel p2){
        p2.setBackground(new Color(0,102,102));
    }
    private void HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseEntered
        resetColor(Home);
    }//GEN-LAST:event_HomeMouseEntered

    private void HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseExited
        setColor(Home);
    }//GEN-LAST:event_HomeMouseExited

    private void AppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppMouseEntered
        resetColor(App);
    }//GEN-LAST:event_AppMouseEntered

    private void AppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppMouseExited
        setColor(App);
    }//GEN-LAST:event_AppMouseExited

    private void MentorsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MentorsMouseEntered
        resetColor(Mentors);
    }//GEN-LAST:event_MentorsMouseEntered

    private void MentorsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MentorsMouseExited
        setColor(Mentors);
    }//GEN-LAST:event_MentorsMouseExited

    private void AccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccMouseEntered
        resetColor(Acc);
    }//GEN-LAST:event_AccMouseEntered

    private void AccMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccMouseExited
        setColor(Acc);
    }//GEN-LAST:event_AccMouseExited

    private void LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseEntered
        resetColor(Logout);
    }//GEN-LAST:event_LogoutMouseEntered

    private void LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseExited
        setColor(Logout);
    }//GEN-LAST:event_LogoutMouseExited

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        session.getInstance().clearSession();
        JOptionPane.showMessageDialog(null, "Logged out successfully!");
        new LoginPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutMouseClicked

    private void SearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseExited
        setColor(Search);
    }//GEN-LAST:event_SearchMouseExited

    private void SearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseEntered
        resetColor(Search);
    }//GEN-LAST:event_SearchMouseEntered

    private void SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseClicked

        config conf = new config();

        String keyword = SearchText.getText().trim();

        if (keyword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a name or email to search.");
            return;
        }

        String sql = "SELECT a_id, name, email, password, type, status " +
        "FROM energy_log WHERE name LIKE '%" + keyword + "%' " +
        "OR email LIKE '%" + keyword + "%'";

        conf.displayData(sql, logTable);

        if (logTable.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Doesn't Exist");
        }
    }//GEN-LAST:event_SearchMouseClicked

    private void SearchTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchTextKeyTyped
        String searchText = SearchText.getText();

        String sql = "SELECT * FROM energy_log WHERE "
                + "logs_id LIKE ? OR "
                + "u_id LIKE ? OR "
                + "task LIKE ? OR "
                + "energy_level LIKE ? OR "
                + "date LIKE ? "
                ;

        config conf = new config();

        conf.displayData(sql, logTable,
                "%" + searchText + "%",
                "%" + searchText + "%",
                "%" + searchText + "%",
                "%" + searchText + "%",
                "%" + searchText + "%"
        );
    }//GEN-LAST:event_SearchTextKeyTyped

    private void SearchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTextActionPerformed

    private void DeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseExited
        setColor(Delete);
    }//GEN-LAST:event_DeleteMouseExited

    private void DeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseEntered
        resetColor(Delete);
    }//GEN-LAST:event_DeleteMouseEntered

    private void DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseClicked
        int row = logTable.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a log first!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete this log?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) return;

        int logId = Integer.parseInt(logTable.getValueAt(row, 0).toString());

        config conf = new config();
        String sql = "DELETE FROM energy_log WHERE logs_id=?";

        conf.addRecord(sql, logId);

        JOptionPane.showMessageDialog(this, "Log deleted successfully!");

        DisplayLog(); 
    }//GEN-LAST:event_DeleteMouseClicked

    private void UdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UdMouseExited
        setColor(Ud);
    }//GEN-LAST:event_UdMouseExited

    private void UdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UdMouseEntered
        resetColor(Ud);
    }//GEN-LAST:event_UdMouseEntered

    private void UdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UdMouseClicked
    int row = logTable.getSelectedRow();

if (row == -1) {
    JOptionPane.showMessageDialog(this, "Please select a record to update.");
    return;
}

int logs_id = Integer.parseInt(logTable.getValueAt(row, 0).toString());
String task = logTable.getValueAt(row, 1).toString();
int energy_level = Integer.parseInt(logTable.getValueAt(row, 2).toString());
String date = logTable.getValueAt(row, 3).toString();

LogUpdate Ud = new LogUpdate(logs_id, task, energy_level, date);
Ud.setVisible(true);
dispose();
    }//GEN-LAST:event_UdMouseClicked

    private void AddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseExited
        setColor(Add);
    }//GEN-LAST:event_AddMouseExited

    private void AddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseEntered
        resetColor(Add);
    }//GEN-LAST:event_AddMouseEntered

    private void AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseClicked
        Add Add = new Add();
        Add.setVisible(true);
        dispose();
    }//GEN-LAST:event_AddMouseClicked

    private void AccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccMouseClicked
        Profile Acc = new Profile();
        Acc.setVisible(true);
        dispose();
    }//GEN-LAST:event_AccMouseClicked

    private void AppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppMouseClicked
        LogEnergy App = new LogEnergy();
        App.setVisible(true);
        dispose();
    }//GEN-LAST:event_AppMouseClicked

    private void MentorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MentorsMouseClicked
        config con = new config();

        session sess = session.getInstance();
        int userId = sess.getUserId();

        String sql = "SELECT mentor_id FROM mentor_client WHERE client_id = ?";

        try {
            PreparedStatement pst = con.connectDB().prepareStatement(sql);
            pst.setInt(1, userId);
            ResultSet rs = pst.executeQuery();

            if (rs.next() && rs.getInt("mentor_id") > 0) {
                new Mentor().setVisible(true);
            } else {
                new Apply().setVisible(true);
            }

            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_MentorsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogEnergy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogEnergy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogEnergy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogEnergy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogEnergy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Acc;
    private javax.swing.JPanel Add;
    private javax.swing.JLabel AddLbl;
    private javax.swing.JPanel App;
    private javax.swing.JPanel Delete;
    private javax.swing.JLabel DeleteLbl;
    private javax.swing.JPanel Home;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel Logout;
    private javax.swing.JPanel Mentors;
    private javax.swing.JPanel Search;
    private javax.swing.JLabel SearchLbl;
    private javax.swing.JTextField SearchText;
    private javax.swing.JPanel Ud;
    private javax.swing.JLabel UpdateLbl;
    private javax.swing.JLabel avgValue;
    private javax.swing.JLabel highestValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable logTable;
    private javax.swing.JLabel lowestValue;
    // End of variables declaration//GEN-END:variables
}
