/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Main.LoginPage;

/**
 *
 * @author Sheena
 */
public class LandingPage extends javax.swing.JFrame {

    /**
     * Creates new form LandingPage
     */
    public LandingPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Background = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        TitleDesc = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        Pic = new javax.swing.JLabel();
        PicBg = new javax.swing.JLabel();
        Energized = new javax.swing.JLabel();
        Balanced = new javax.swing.JLabel();
        Registerbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (3).png"))); // NOI18N
        jLabel2.setToolTipText("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setBackground(new java.awt.Color(0, 51, 51));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Broadway", 2, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("EnergiFy");
        Background.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 330, 40));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled_design-removebg-preview.png"))); // NOI18N
        Background.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 20, 280, 110));

        TitleDesc.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        TitleDesc.setForeground(new java.awt.Color(255, 255, 255));
        TitleDesc.setText("Personal Energy and Productivity Tracker");
        Background.add(TitleDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        Home.setFont(new java.awt.Font("Broadway", 1, 18)); // NOI18N
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setText("HOME");
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Background.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, -1, -1));

        Login.setFont(new java.awt.Font("Broadway", 1, 18)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setText("LOGIN");
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginMouseClicked(evt);
            }
        });
        Background.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 50, -1, -1));

        Pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled_design__4_-removebg-preview.png"))); // NOI18N
        Background.add(Pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, -1));

        PicBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (3).png"))); // NOI18N
        PicBg.setToolTipText("");
        Background.add(PicBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 600, -1));

        Energized.setFont(new java.awt.Font("Broadway", 3, 48)); // NOI18N
        Energized.setForeground(new java.awt.Color(255, 255, 255));
        Energized.setText("Stay Energized");
        Background.add(Energized, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 470, -1));

        Balanced.setFont(new java.awt.Font("Broadway", 3, 48)); // NOI18N
        Balanced.setForeground(new java.awt.Color(255, 255, 255));
        Balanced.setText("Stay Balanced");
        Background.add(Balanced, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 450, -1));

        Registerbtn.setBackground(new java.awt.Color(0, 102, 102));
        Registerbtn.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        Registerbtn.setForeground(new java.awt.Color(255, 255, 255));
        Registerbtn.setText("Register Now!");
        Registerbtn.setBorderPainted(false);
        Registerbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Registerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterbtnActionPerformed(evt);
            }
        });
        Background.add(Registerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 220, 60));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Build better habits by understanding ");
        Background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, 40));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("how your energy changes throughout the day.");
        Background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, 30));

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterbtnActionPerformed
        RegisterPage Registerbtn = new RegisterPage();
        Registerbtn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegisterbtnActionPerformed

    private void LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseClicked
        LoginPage Login = new LoginPage();
        Login.setVisible(true);
        dispose();
    }//GEN-LAST:event_LoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LandingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Balanced;
    private javax.swing.JLabel Energized;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Pic;
    private javax.swing.JLabel PicBg;
    private javax.swing.JButton Registerbtn;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel TitleDesc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
