/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Main.LoginPage;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Sheena
 */
public class LandingPage extends javax.swing.JFrame {

    /**
     * Creates new form LandingPage
     */
    public LandingPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Background = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        TitleDesc = new javax.swing.JLabel();
        Energized = new javax.swing.JLabel();
        Balanced = new javax.swing.JLabel();
        Text = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();
        AboutPanel = new javax.swing.JPanel();
        AboutLbl = new javax.swing.JLabel();
        LoginPanel = new javax.swing.JPanel();
        LoginLbl = new javax.swing.JLabel();
        SignPanel = new javax.swing.JPanel();
        SignUpLbl = new javax.swing.JLabel();
        StartPanel = new javax.swing.JPanel();
        StartLbl = new javax.swing.JLabel();
        VisualIcon = new javax.swing.JLabel();
        Bg = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (3).png"))); // NOI18N
        jLabel2.setToolTipText("");

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1300, 737));
        setMinimumSize(new java.awt.Dimension(1300, 737));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setBackground(new java.awt.Color(0, 51, 51));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Broadway", 2, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("EnergiFy");
        Background.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 190, 40));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        Background.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 40, 280, 110));

        TitleDesc.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        TitleDesc.setForeground(new java.awt.Color(255, 255, 255));
        TitleDesc.setText("Personal Energy and Productivity Tracker");
        Background.add(TitleDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        Energized.setFont(new java.awt.Font("Broadway", 3, 48)); // NOI18N
        Energized.setForeground(new java.awt.Color(255, 255, 255));
        Energized.setText("Stay Energized");
        Background.add(Energized, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 470, -1));

        Balanced.setFont(new java.awt.Font("Broadway", 3, 48)); // NOI18N
        Balanced.setForeground(new java.awt.Color(255, 255, 255));
        Balanced.setText("Stay Balanced");
        Background.add(Balanced, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 450, -1));

        Text.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        Text.setForeground(new java.awt.Color(255, 255, 255));
        Text.setText("Build better habits by understanding ");
        Background.add(Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, 40));

        Text2.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        Text2.setForeground(new java.awt.Color(255, 255, 255));
        Text2.setText("how your energy changes throughout the day.");
        Background.add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, 30));

        AboutPanel.setBackground(new java.awt.Color(0, 51, 51));
        AboutPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        AboutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AboutPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AboutPanelMouseExited(evt);
            }
        });
        AboutPanel.setLayout(null);

        AboutLbl.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        AboutLbl.setForeground(new java.awt.Color(255, 255, 255));
        AboutLbl.setText("ABOUT");
        AboutLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AboutPanel.add(AboutLbl);
        AboutLbl.setBounds(34, 16, 88, 29);

        Background.add(AboutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, 160, 60));

        LoginPanel.setBackground(new java.awt.Color(0, 51, 51));
        LoginPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        LoginPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginPanelMouseExited(evt);
            }
        });
        LoginPanel.setLayout(null);

        LoginLbl.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        LoginLbl.setForeground(new java.awt.Color(255, 255, 255));
        LoginLbl.setText("LOGIN");
        LoginPanel.add(LoginLbl);
        LoginLbl.setBounds(40, 20, 81, 20);

        Background.add(LoginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 50, 160, 60));

        SignPanel.setBackground(new java.awt.Color(0, 51, 51));
        SignPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        SignPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignPanelMouseExited(evt);
            }
        });
        SignPanel.setLayout(null);

        SignUpLbl.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        SignUpLbl.setForeground(new java.awt.Color(255, 255, 255));
        SignUpLbl.setText("SIGNUP");
        SignPanel.add(SignUpLbl);
        SignUpLbl.setBounds(32, 16, 97, 29);

        Background.add(SignPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 50, 160, 60));

        StartPanel.setBackground(new java.awt.Color(0, 51, 51));
        StartPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        StartPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StartPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StartPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StartPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StartPanelMouseExited(evt);
            }
        });
        StartPanel.setLayout(null);

        StartLbl.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        StartLbl.setForeground(new java.awt.Color(255, 255, 255));
        StartLbl.setText("Get Started");
        StartPanel.add(StartLbl);
        StartLbl.setBounds(60, 30, 144, 20);

        Background.add(StartPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 270, 80));

        VisualIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg (5).png"))); // NOI18N
        Background.add(VisualIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        Bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.png"))); // NOI18N
        Background.add(Bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 740));

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void setColor(JPanel p){
    p.setBackground(new Color(0,51,51));
    }
    public void resetColor(JPanel p){
    p.setBackground(new Color(0,102,102));
    }
    
    private void AboutPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutPanelMouseEntered
        resetColor(AboutPanel);
    }//GEN-LAST:event_AboutPanelMouseEntered

    private void AboutPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutPanelMouseExited
        setColor(AboutPanel);
    }//GEN-LAST:event_AboutPanelMouseExited

    private void LoginPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginPanelMouseClicked
        LoginPage LoginPanel = new LoginPage();
        LoginPanel.setVisible(true);
        dispose();
    }//GEN-LAST:event_LoginPanelMouseClicked

    private void LoginPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginPanelMouseEntered
        resetColor(LoginPanel);
    }//GEN-LAST:event_LoginPanelMouseEntered

    private void LoginPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginPanelMouseExited
        setColor(LoginPanel);
    }//GEN-LAST:event_LoginPanelMouseExited

    private void SignPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignPanelMouseEntered
        resetColor(SignPanel);
    }//GEN-LAST:event_SignPanelMouseEntered

    private void SignPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignPanelMouseExited
        setColor(SignPanel);
    }//GEN-LAST:event_SignPanelMouseExited

    private void SignPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignPanelMouseClicked
        RegisterPage SignPanel = new RegisterPage();
        SignPanel.setVisible(true);
        dispose();
    }//GEN-LAST:event_SignPanelMouseClicked

    private void StartPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartPanelMouseEntered
        resetColor(StartPanel);
    }//GEN-LAST:event_StartPanelMouseEntered

    private void StartPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartPanelMouseExited
        setColor(StartPanel);
    }//GEN-LAST:event_StartPanelMouseExited

    private void StartPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartPanelMouseClicked
        RegisterPage StartPanel = new RegisterPage();
        StartPanel.setVisible(true);
        dispose();
    }//GEN-LAST:event_StartPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LandingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AboutLbl;
    private javax.swing.JPanel AboutPanel;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Balanced;
    private javax.swing.JLabel Bg;
    private javax.swing.JLabel Energized;
    private javax.swing.JLabel LoginLbl;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel SignPanel;
    private javax.swing.JLabel SignUpLbl;
    private javax.swing.JLabel StartLbl;
    private javax.swing.JPanel StartPanel;
    private javax.swing.JLabel Text;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel TitleDesc;
    private javax.swing.JLabel VisualIcon;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
