/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Admin.AdminDashboard;
import Config.config;
import Mentor.MentorDashboard;
import User.UserDashboard;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sheena
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        TitleDesc = new javax.swing.JLabel();
        Bot = new javax.swing.JLabel();
        Text = new javax.swing.JLabel();
        Top = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Email = new javax.swing.JTextField();
        LoginTitle = new javax.swing.JLabel();
        SignUpbtn = new javax.swing.JLabel();
        Acc = new javax.swing.JLabel();
        NameLbl = new javax.swing.JLabel();
        ShowIcon = new javax.swing.JLabel();
        PassLbl = new javax.swing.JLabel();
        Pass = new javax.swing.JPasswordField();
        Forgot = new javax.swing.JLabel();
        LoginButton = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        BackHome = new javax.swing.JLabel();
        Bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1300, 737));
        setMinimumSize(new java.awt.Dimension(1300, 737));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Broadway", 2, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("EnergiFy");
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 180, 40));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 280, 110));

        TitleDesc.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        TitleDesc.setForeground(new java.awt.Color(255, 255, 255));
        TitleDesc.setText("Personal Energy and Productivity");
        jPanel1.add(TitleDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        Bot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bot.png"))); // NOI18N
        jPanel1.add(Bot, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 440, 320));

        Text.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        Text.setForeground(new java.awt.Color(255, 255, 255));
        Text.setText("Tracker");
        jPanel1.add(Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, -1));

        Top.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/top.png"))); // NOI18N
        jPanel1.add(Top, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 410, -1));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        jPanel2.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 390, 60));

        LoginTitle.setFont(new java.awt.Font("Bookman Old Style", 1, 48)); // NOI18N
        LoginTitle.setForeground(new java.awt.Color(255, 255, 255));
        LoginTitle.setText("LOGIN ");
        jPanel2.add(LoginTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        SignUpbtn.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        SignUpbtn.setForeground(new java.awt.Color(255, 255, 255));
        SignUpbtn.setText("Sign up");
        SignUpbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignUpbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignUpbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignUpbtnMouseExited(evt);
            }
        });
        jPanel2.add(SignUpbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 70, -1));

        Acc.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        Acc.setForeground(new java.awt.Color(255, 255, 255));
        Acc.setText("Don't have an account?");
        jPanel2.add(Acc, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        NameLbl.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        NameLbl.setForeground(new java.awt.Color(255, 255, 255));
        NameLbl.setText("Email");
        jPanel2.add(NameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        ShowIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled_design__11_-removebg-preview.png"))); // NOI18N
        ShowIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ShowIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowIconMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ShowIconMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ShowIconMouseReleased(evt);
            }
        });
        jPanel2.add(ShowIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, 50, 60));

        PassLbl.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        PassLbl.setForeground(new java.awt.Color(255, 255, 255));
        PassLbl.setText("Password");
        jPanel2.add(PassLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, -1));

        Pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassActionPerformed(evt);
            }
        });
        jPanel2.add(Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 390, 60));

        Forgot.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        Forgot.setForeground(new java.awt.Color(255, 255, 255));
        Forgot.setText("Forgot Password?");
        Forgot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Forgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ForgotMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ForgotMouseExited(evt);
            }
        });
        jPanel2.add(Forgot, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 190, -1));

        LoginButton.setBackground(new java.awt.Color(0, 51, 51));
        LoginButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        LoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginButtonMouseExited(evt);
            }
        });
        LoginButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("LOGIN");
        LoginButton.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, 20));

        jPanel2.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 560, 220, 60));

        BackHome.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        BackHome.setForeground(new java.awt.Color(255, 255, 255));
        BackHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg (9).png"))); // NOI18N
        BackHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackHomeMouseExited(evt);
            }
        });
        jPanel2.add(BackHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 60));

        Bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.png"))); // NOI18N
        jPanel2.add(Bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 850, 740));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void PassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassActionPerformed

    private void ShowIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowIconMouseClicked
        ShowIcon.setVisible(true);
        Pass.setEchoChar((char)0);
    }//GEN-LAST:event_ShowIconMouseClicked

    private void ShowIconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowIconMousePressed
        ShowIcon.setVisible(true);
        Pass.setEchoChar((char)0);
    }//GEN-LAST:event_ShowIconMousePressed

    private void ShowIconMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowIconMouseReleased

    }//GEN-LAST:event_ShowIconMouseReleased

    private void BackHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackHomeMouseClicked
        LandingPage BackHome = new LandingPage();
        BackHome.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackHomeMouseClicked

    private void SignUpbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpbtnMouseClicked
        RegisterPage SignUpbtn = new RegisterPage();
        SignUpbtn.setVisible(true);
        dispose();
    }//GEN-LAST:event_SignUpbtnMouseClicked
    public void setColor(JPanel p){
        p.setBackground(new Color(0,51,51));
    }
    public void resetColor(JPanel pl){
        pl.setBackground(new Color(0,102,102));
    }
    private void LoginButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseEntered
        resetColor(LoginButton);
    }//GEN-LAST:event_LoginButtonMouseEntered

    private void LoginButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseExited
        setColor(LoginButton);
    }//GEN-LAST:event_LoginButtonMouseExited

    private void LoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseClicked
        String email = Email.getText();
        String password = Pass.getText();

        if (email.equals("") || password.equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill in all fields!");
            return;
        }

        String sql = "SELECT * FROM tbl_accts WHERE email = ? AND password = ?";

        try (
            java.sql.Connection conn = Config.config.connectDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        ) {

            pst.setString(1, email);
            pst.setString(2, password);

            java.sql.ResultSet rs = pst.executeQuery();

            if (!rs.next()) {
                JOptionPane.showMessageDialog(null, "Invalid email or password!");
                return;
            }

            if (!rs.getString("status").equalsIgnoreCase("Active")) {
                JOptionPane.showMessageDialog(
                    null,
                    "Your account is inactive. Please contact the administrator."
                );
                return;
            }

            Config.session.setSession(
                rs.getInt("a_id"),
                rs.getString("name"),
                rs.getString("lname"),
                rs.getString("uname"),
                rs.getString("email"),
                rs.getString("type"),
                rs.getString("status")
            );

            JOptionPane.showMessageDialog(null, "LOGIN SUCCESS!");

            String userType = rs.getString("type");

            if (userType.equalsIgnoreCase("Admin")) {
                new AdminDashboard().setVisible(true);
            } else if (userType.equalsIgnoreCase("User")) {
                new UserDashboard().setVisible(true);
            } else if (userType.equalsIgnoreCase("Mentor")) {
                new MentorDashboard().setVisible(true);
            }

            dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Login Error: " + e.getMessage());
        }
    }//GEN-LAST:event_LoginButtonMouseClicked

    private void BackHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackHomeMouseEntered
        BackHome.setForeground(new Color(255,153,51));
    }//GEN-LAST:event_BackHomeMouseEntered

    private void SignUpbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpbtnMouseEntered
        SignUpbtn.setForeground(new Color(255,153,51));
    }//GEN-LAST:event_SignUpbtnMouseEntered

    private void ForgotMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotMouseEntered
        Forgot.setForeground(new Color(255,153,51));
    }//GEN-LAST:event_ForgotMouseEntered

    private void BackHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackHomeMouseExited
        BackHome.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_BackHomeMouseExited

    private void SignUpbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpbtnMouseExited
        SignUpbtn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_SignUpbtnMouseExited

    private void ForgotMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotMouseExited
        Forgot.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_ForgotMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Acc;
    private javax.swing.JLabel BackHome;
    private javax.swing.JLabel Bg;
    private javax.swing.JLabel Bot;
    private javax.swing.JTextField Email;
    private javax.swing.JLabel Forgot;
    private javax.swing.JPanel LoginButton;
    private javax.swing.JLabel LoginTitle;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel NameLbl;
    private javax.swing.JPasswordField Pass;
    private javax.swing.JLabel PassLbl;
    private javax.swing.JLabel ShowIcon;
    private javax.swing.JLabel SignUpbtn;
    private javax.swing.JLabel Text;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel TitleDesc;
    private javax.swing.JLabel Top;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    // End of variables declaration//GEN-END:variables
}
