/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Config.config;
import Main.LoginPage;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Sheena
 */
public class RegisterPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public RegisterPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        TitleDesc = new javax.swing.JLabel();
        Text = new javax.swing.JLabel();
        Bot = new javax.swing.JLabel();
        Top = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Email = new javax.swing.JTextField();
        RegisterTitle = new javax.swing.JLabel();
        Loginbtn = new javax.swing.JLabel();
        Acc = new javax.swing.JLabel();
        EmailLbl = new javax.swing.JLabel();
        CpassLbl = new javax.swing.JLabel();
        Forgot = new javax.swing.JLabel();
        Register = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Fname = new javax.swing.JTextField();
        FullNameLbl = new javax.swing.JLabel();
        PassLbl = new javax.swing.JLabel();
        Show = new javax.swing.JLabel();
        Pass = new javax.swing.JPasswordField();
        BackHome = new javax.swing.JLabel();
        FullNameLbl1 = new javax.swing.JLabel();
        Lname = new javax.swing.JTextField();
        Uname1 = new javax.swing.JTextField();
        Bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 737));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Broadway", 2, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("EnergiFy");
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 180, 40));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 280, 110));

        TitleDesc.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        TitleDesc.setForeground(new java.awt.Color(255, 255, 255));
        TitleDesc.setText("Personal Energy and Productivity");
        jPanel1.add(TitleDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        Text.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        Text.setForeground(new java.awt.Color(255, 255, 255));
        Text.setText("Tracker");
        jPanel1.add(Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, -1));

        Bot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bot.png"))); // NOI18N
        jPanel1.add(Bot, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 440, 320));

        Top.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/top.png"))); // NOI18N
        jPanel1.add(Top, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 410, -1));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Email.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        jPanel2.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 400, 40));

        RegisterTitle.setFont(new java.awt.Font("Bookman Old Style", 1, 48)); // NOI18N
        RegisterTitle.setForeground(new java.awt.Color(255, 255, 255));
        RegisterTitle.setText("REGISTER");
        jPanel2.add(RegisterTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 270, -1));

        Loginbtn.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        Loginbtn.setForeground(new java.awt.Color(255, 255, 255));
        Loginbtn.setText("Login");
        Loginbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Loginbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginbtnMouseExited(evt);
            }
        });
        jPanel2.add(Loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 50, -1));

        Acc.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        Acc.setForeground(new java.awt.Color(255, 255, 255));
        Acc.setText("Already have an account?");
        jPanel2.add(Acc, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, 20));

        EmailLbl.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        EmailLbl.setForeground(new java.awt.Color(255, 255, 255));
        EmailLbl.setText("Username");
        jPanel2.add(EmailLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, 20));

        CpassLbl.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        CpassLbl.setForeground(new java.awt.Color(255, 255, 255));
        CpassLbl.setText("Email Address");
        jPanel2.add(CpassLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, -1, 20));

        Forgot.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        Forgot.setForeground(new java.awt.Color(255, 255, 255));
        Forgot.setText("Forgot Password?");
        Forgot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Forgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ForgotMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ForgotMouseExited(evt);
            }
        });
        jPanel2.add(Forgot, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 570, 160, 20));

        Register.setBackground(new java.awt.Color(0, 51, 51));
        Register.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegisterMouseExited(evt);
            }
        });
        Register.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("REGISTER");
        Register.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 140, 20));

        jPanel2.add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 620, 210, 60));

        Fname.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        Fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnameActionPerformed(evt);
            }
        });
        jPanel2.add(Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 400, 40));

        FullNameLbl.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        FullNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        FullNameLbl.setText("First Name");
        jPanel2.add(FullNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, 20));

        PassLbl.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        PassLbl.setForeground(new java.awt.Color(255, 255, 255));
        PassLbl.setText("Password");
        jPanel2.add(PassLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, -1, 20));

        Show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled_design__11_-removebg-preview.png"))); // NOI18N
        Show.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ShowMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ShowMouseReleased(evt);
            }
        });
        jPanel2.add(Show, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, 50, 80));

        Pass.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        Pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassActionPerformed(evt);
            }
        });
        jPanel2.add(Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 400, 40));

        BackHome.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        BackHome.setForeground(new java.awt.Color(255, 255, 255));
        BackHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg (9).png"))); // NOI18N
        BackHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackHomeMouseExited(evt);
            }
        });
        jPanel2.add(BackHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 60));

        FullNameLbl1.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        FullNameLbl1.setForeground(new java.awt.Color(255, 255, 255));
        FullNameLbl1.setText("Last Name");
        jPanel2.add(FullNameLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, 20));

        Lname.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        Lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LnameActionPerformed(evt);
            }
        });
        jPanel2.add(Lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 400, 40));

        Uname1.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        Uname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Uname1ActionPerformed(evt);
            }
        });
        jPanel2.add(Uname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 400, 40));

        Bg.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        Bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.png"))); // NOI18N
        jPanel2.add(Bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 850, 740));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void FnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FnameActionPerformed

    private void ShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowMouseClicked
        Show.setVisible(true);
        Pass.setEchoChar((char)0);
    }//GEN-LAST:event_ShowMouseClicked

    private void ShowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowMousePressed
        Show.setVisible(true);
        Pass.setEchoChar((char)0);
    }//GEN-LAST:event_ShowMousePressed

    private void ShowMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ShowMouseReleased

    private void PassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassActionPerformed

    private void BackHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackHomeMouseClicked
        LandingPage BackHome = new LandingPage();
        BackHome.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackHomeMouseClicked

    private void LoginbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginbtnMouseClicked
        LoginPage Loginbtn = new LoginPage();
        Loginbtn.setVisible(true);
        dispose();
    }//GEN-LAST:event_LoginbtnMouseClicked

    private void RegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterMouseClicked
        config con = new config();

        String sql = "INSERT INTO tbl_accts (name, lname, uname, email, password, type, status) VALUES (?,?,?,?,?,?,?)";

        String email = Email.getText();
        String password = Pass.getText();

        if (email.equals("") || password.equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill in all fields!");
            return;
        }

        con.addRecord(
            sql,
            Fname.getText(),   
            Lname.getText(),  
            Email.getText(),  
            Email.getText(),   
            Pass.getText(),   
            "User",           
            "Pending"         
        );

        JOptionPane.showMessageDialog(null, "Record Added!");

        Fname.setText("");
        Lname.setText("");
        Email.setText("");
        Email.setText("");
        Pass.setText("");
    }//GEN-LAST:event_RegisterMouseClicked

    private void BackHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackHomeMouseEntered
        BackHome.setForeground(new Color(255,153,51));
    }//GEN-LAST:event_BackHomeMouseEntered

    private void BackHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackHomeMouseExited
        BackHome.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_BackHomeMouseExited

    private void LoginbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginbtnMouseEntered
        Loginbtn.setForeground(new Color(255,153,51));
    }//GEN-LAST:event_LoginbtnMouseEntered

    private void LoginbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginbtnMouseExited
        Loginbtn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_LoginbtnMouseExited

    private void ForgotMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotMouseEntered
        Forgot.setForeground(new Color(255,153,51));
    }//GEN-LAST:event_ForgotMouseEntered

    private void ForgotMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotMouseExited
        Forgot.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_ForgotMouseExited

    private void RegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterMouseEntered
        Register.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_RegisterMouseEntered

    private void RegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterMouseExited
        Register.setBackground(new Color(0,51,51));
    }//GEN-LAST:event_RegisterMouseExited

    private void LnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LnameActionPerformed

    private void Uname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Uname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Uname1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Acc;
    private javax.swing.JLabel BackHome;
    private javax.swing.JLabel Bg;
    private javax.swing.JLabel Bot;
    private javax.swing.JLabel CpassLbl;
    private javax.swing.JTextField Email;
    private javax.swing.JLabel EmailLbl;
    private javax.swing.JTextField Fname;
    private javax.swing.JLabel Forgot;
    private javax.swing.JLabel FullNameLbl;
    private javax.swing.JLabel FullNameLbl1;
    private javax.swing.JTextField Lname;
    private javax.swing.JLabel Loginbtn;
    private javax.swing.JLabel Logo;
    private javax.swing.JPasswordField Pass;
    private javax.swing.JLabel PassLbl;
    private javax.swing.JPanel Register;
    private javax.swing.JLabel RegisterTitle;
    private javax.swing.JLabel Show;
    private javax.swing.JLabel Text;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel TitleDesc;
    private javax.swing.JLabel Top;
    private javax.swing.JTextField Uname1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    // End of variables declaration//GEN-END:variables
}
