/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Config.config;
import Main.LandingPage;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Sheena
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        DisplayUser();
    }
    
    void DisplayUser(){
    
        config con = new config();
        String sql = "SELECT name, email, type, status FROM tbl_accts";
        con.displayData(sql, UserTable);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Home = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        App = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        User = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Mentor = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        System = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Acc = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Logout = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        UserTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        Bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1300, 737));
        setMinimumSize(new java.awt.Dimension(1300, 737));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        Logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoMouseClicked(evt);
            }
        });
        jPanel2.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 30, 290, 110));

        jLabel1.setFont(new java.awt.Font("Broadway", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EnergiFy");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 180, 30));

        Home.setBackground(new java.awt.Color(0, 51, 51));
        Home.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeMouseExited(evt);
            }
        });
        Home.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HOME");
        Home.add(jLabel2);
        jLabel2.setBounds(139, 16, 79, 29);

        jPanel2.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 360, 60));

        App.setBackground(new java.awt.Color(0, 51, 51));
        App.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        App.setForeground(new java.awt.Color(255, 255, 255));
        App.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        App.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AppMouseExited(evt);
            }
        });
        App.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("APPLICATIONS");
        App.add(jLabel3);
        jLabel3.setBounds(85, 16, 189, 29);

        jPanel2.add(App, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 360, 60));

        User.setBackground(new java.awt.Color(0, 51, 51));
        User.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        User.setForeground(new java.awt.Color(255, 255, 255));
        User.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UserMouseExited(evt);
            }
        });
        User.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("USERS");
        User.add(jLabel4);
        jLabel4.setBounds(134, 16, 86, 29);

        jPanel2.add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 360, 60));

        Mentor.setBackground(new java.awt.Color(0, 51, 51));
        Mentor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Mentor.setForeground(new java.awt.Color(255, 255, 255));
        Mentor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Mentor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MentorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MentorMouseExited(evt);
            }
        });
        Mentor.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MENTOR ASSIGNMENTS");
        Mentor.add(jLabel5);
        jLabel5.setBounds(30, 20, 308, 20);

        jPanel2.add(Mentor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 360, 60));

        System.setBackground(new java.awt.Color(0, 51, 51));
        System.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        System.setForeground(new java.awt.Color(255, 255, 255));
        System.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        System.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SystemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SystemMouseExited(evt);
            }
        });
        System.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SYSTEM SETTINGS");
        System.add(jLabel6);
        jLabel6.setBounds(57, 16, 244, 29);

        jPanel2.add(System, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 360, 60));

        Acc.setBackground(new java.awt.Color(0, 51, 51));
        Acc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Acc.setForeground(new java.awt.Color(255, 255, 255));
        Acc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Acc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AccMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AccMouseExited(evt);
            }
        });
        Acc.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ACCOUNT");
        Acc.add(jLabel7);
        jLabel7.setBounds(114, 16, 125, 29);

        jPanel2.add(Acc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 360, 60));

        Logout.setBackground(new java.awt.Color(0, 51, 51));
        Logout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutMouseExited(evt);
            }
        });
        Logout.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("LOGOUT");
        Logout.add(jLabel8);
        jLabel8.setBounds(126, 16, 107, 29);

        jPanel2.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 360, 60));

        jScrollPane1.setBackground(new java.awt.Color(0, 51, 51));
        jScrollPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        jScrollPane1.setToolTipText("");
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel6.setBackground(new java.awt.Color(0, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabel10.setText("Pending Applications");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 10, 260, 29);

        jLabel14.setFont(new java.awt.Font("Bookman Old Style", 0, 48)); // NOI18N
        jLabel14.setText("3");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(10, 60, 30, 50);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg (10).png"))); // NOI18N
        jPanel3.add(jLabel20);
        jLabel20.setBounds(0, 0, 430, 180);

        jPanel6.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 410, 150));

        jPanel4.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabel11.setText("Active Users");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(10, 10, 160, 29);

        jLabel15.setFont(new java.awt.Font("Bookman Old Style", 0, 48)); // NOI18N
        jLabel15.setText("2");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(10, 60, 30, 60);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg (10).png"))); // NOI18N
        jPanel4.add(jLabel21);
        jLabel21.setBounds(10, 0, 430, 180);

        jPanel6.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 420, 150));

        jPanel5.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabel12.setText("Active Mentors");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(10, 10, 200, 29);

        jLabel16.setFont(new java.awt.Font("Bookman Old Style", 0, 48)); // NOI18N
        jLabel16.setText("1");
        jPanel5.add(jLabel16);
        jLabel16.setBounds(10, 50, 30, 60);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg (10).png"))); // NOI18N
        jPanel5.add(jLabel22);
        jLabel22.setBounds(0, 0, 430, 180);

        jPanel6.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 410, 150));

        jPanel7.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabel13.setText("Unassigned Students");
        jPanel7.add(jLabel13);
        jLabel13.setBounds(10, 10, 270, 29);

        jLabel17.setFont(new java.awt.Font("Bookman Old Style", 0, 48)); // NOI18N
        jLabel17.setText("1");
        jPanel7.add(jLabel17);
        jLabel17.setBounds(10, 50, 30, 60);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg (10).png"))); // NOI18N
        jPanel7.add(jLabel19);
        jLabel19.setBounds(10, 0, 440, 180);

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 420, 150));

        UserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(UserTable);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 860, 320));

        jScrollPane1.setViewportView(jPanel6);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 940, 570));

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(" ADMIN DASHBOARD");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, -1, -1));

        Bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.png"))); // NOI18N
        jPanel2.add(Bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 1300, 740));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 740));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void setColor(JPanel p){
        p.setBackground(new Color(0,51,51));
    }
    public void resetColor(JPanel p2){
        p2.setBackground(new Color(0,102,102));
    }
    private void HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseEntered
        resetColor(Home);
    }//GEN-LAST:event_HomeMouseEntered

    private void HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseExited
        setColor(Home);
    }//GEN-LAST:event_HomeMouseExited

    private void AppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppMouseEntered
        resetColor(App);
    }//GEN-LAST:event_AppMouseEntered

    private void AppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppMouseExited
        setColor(App);
    }//GEN-LAST:event_AppMouseExited

    private void UserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserMouseEntered
        resetColor(User);
    }//GEN-LAST:event_UserMouseEntered

    private void UserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserMouseExited
        setColor(User);
    }//GEN-LAST:event_UserMouseExited

    private void MentorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MentorMouseEntered
        resetColor(Mentor);
    }//GEN-LAST:event_MentorMouseEntered

    private void MentorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MentorMouseExited
        setColor(Mentor);
    }//GEN-LAST:event_MentorMouseExited

    private void SystemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SystemMouseEntered
        resetColor(System);
    }//GEN-LAST:event_SystemMouseEntered

    private void SystemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SystemMouseExited
        setColor(System);
    }//GEN-LAST:event_SystemMouseExited

    private void AccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccMouseEntered
        resetColor(Acc);
    }//GEN-LAST:event_AccMouseEntered

    private void AccMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccMouseExited
        setColor(Acc);
    }//GEN-LAST:event_AccMouseExited

    private void LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseEntered
        resetColor(Logout);
    }//GEN-LAST:event_LogoutMouseEntered

    private void LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseExited
        setColor(Logout);
    }//GEN-LAST:event_LogoutMouseExited

    private void UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserMouseClicked
        Users User = new Users();
        User.setVisible(true);
        dispose();
    }//GEN-LAST:event_UserMouseClicked

    private void LogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoMouseClicked
        LandingPage Logo = new LandingPage();
        Logo.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Acc;
    private javax.swing.JPanel App;
    private javax.swing.JLabel Bg;
    private javax.swing.JPanel Home;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel Logout;
    private javax.swing.JPanel Mentor;
    private javax.swing.JPanel System;
    private javax.swing.JPanel User;
    private javax.swing.JTable UserTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
