/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Main.LandingPage;
import java.awt.Color;
import javax.swing.JPanel;
import Config.session;
import Admin.AdminDashboard;
import Main.LoginPage;
import javax.swing.JOptionPane;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author USER24
 */
public class AdminProfile extends javax.swing.JFrame {

    /**
     * Creates new form AdminProfile
     */
    session sess = session.getInstance();
    public AdminProfile() {
        if (session.isInstanceEmpty() || sess.getUserId() == 0) {
            JOptionPane.showMessageDialog(null, "Login Required!");
            new LoginPage().setVisible(true);
            dispose();
            return;
        }
        initComponents();
        loadProfile();
    }
    
    private void loadProfile() {
        Namelbl.setText(sess.getName());
        Emaillbl.setText(sess.getEmail());
        Typelbl.setText(sess.getType());
        Usernm.setText(sess.getUname());
        Idlbl.setText(String.valueOf(sess.getUserId()));

     try (java.sql.Connection con = Config.config.connectDB();
     PreparedStatement pst = con.prepareStatement(
             "SELECT image FROM tbl_accts WHERE a_id=?")) {

    pst.setInt(1, sess.getUserId());

    try (ResultSet rs = pst.executeQuery()) {

        if (rs.next()) {
            String path = rs.getString("image");

            if (path != null && !path.isEmpty()) {
                ImageIcon icon = new ImageIcon(path);
                Image img = icon.getImage().getScaledInstance(
                        Pics.getWidth(),
                        Pics.getHeight(),
                        Image.SCALE_SMOOTH
                );
                Pics.setIcon(new ImageIcon(img));
            }
        }
    }

} catch (Exception e) {
    e.printStackTrace();
}
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Home = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Acc = new javax.swing.JPanel();
        AccLbl = new javax.swing.JLabel();
        Logout = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        NameLbl = new javax.swing.JLabel();
        EmailLbl = new javax.swing.JLabel();
        TypeLbl = new javax.swing.JLabel();
        Namelbl = new javax.swing.JLabel();
        Emaillbl = new javax.swing.JLabel();
        Typelbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Pics = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Idlbl = new javax.swing.JLabel();
        Usernm = new javax.swing.JLabel();
        Edit = new javax.swing.JPanel();
        Editlbl = new javax.swing.JLabel();
        Reports = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Out = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        App = new javax.swing.JPanel();
        AppLbl = new javax.swing.JLabel();
        Mentor = new javax.swing.JPanel();
        AssignLbl = new javax.swing.JLabel();
        User = new javax.swing.JPanel();
        UsersLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(1300, 737));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        Logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoMouseClicked(evt);
            }
        });
        jPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 30, 290, 110));

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ADMIN PROFILE");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Broadway", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EnergiFy");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 180, 30));

        Home.setBackground(new java.awt.Color(0, 51, 51));
        Home.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeMouseExited(evt);
            }
        });
        Home.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HOME");
        Home.add(jLabel2);
        jLabel2.setBounds(139, 16, 79, 29);

        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 360, 60));

        Acc.setBackground(new java.awt.Color(16, 79, 79));
        Acc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Acc.setForeground(new java.awt.Color(255, 255, 255));
        Acc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Acc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AccMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AccMouseExited(evt);
            }
        });
        Acc.setLayout(null);

        AccLbl.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        AccLbl.setForeground(new java.awt.Color(255, 255, 255));
        AccLbl.setText("ACCOUNT");
        Acc.add(AccLbl);
        AccLbl.setBounds(114, 16, 125, 29);

        jPanel1.add(Acc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 360, 60));

        Logout.setBackground(new java.awt.Color(0, 51, 51));
        Logout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutMouseExited(evt);
            }
        });
        Logout.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("LOGOUT");
        Logout.add(jLabel8);
        jLabel8.setBounds(126, 16, 107, 29);

        jPanel1.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 360, 60));

        jPanel2.setBackground(new java.awt.Color(16, 79, 79));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameLbl.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        NameLbl.setForeground(new java.awt.Color(255, 255, 255));
        NameLbl.setText("Name:");
        jPanel2.add(NameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));

        EmailLbl.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        EmailLbl.setForeground(new java.awt.Color(255, 255, 255));
        EmailLbl.setText("Email:");
        jPanel2.add(EmailLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, 20));

        TypeLbl.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        TypeLbl.setForeground(new java.awt.Color(255, 255, 255));
        TypeLbl.setText("Type:");
        jPanel2.add(TypeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, -1, -1));

        Namelbl.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        Namelbl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(Namelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 220, 40));

        Emaillbl.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        Emaillbl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(Emaillbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 220, 40));

        Typelbl.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        Typelbl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(Typelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 220, 40));

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setLayout(null);

        Pics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg (11).png"))); // NOI18N
        jPanel3.add(Pics);
        Pics.setBounds(50, 30, 200, 200);

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 310, 260));

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, -1, 20));

        Idlbl.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        Idlbl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(Idlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 90, 40));

        Usernm.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        Usernm.setForeground(new java.awt.Color(255, 255, 255));
        Usernm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(Usernm, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 190, 30));

        Edit.setBackground(new java.awt.Color(0, 51, 51));
        Edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditMouseExited(evt);
            }
        });
        Edit.setLayout(null);

        Editlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/7_2.png"))); // NOI18N
        Editlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditlblMouseClicked(evt);
            }
        });
        Edit.add(Editlbl);
        Editlbl.setBounds(0, 0, 190, 180);

        jPanel2.add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 190, 180));

        Reports.setBackground(new java.awt.Color(0, 51, 51));
        Reports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Reports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReportsMouseExited(evt);
            }
        });
        Reports.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/8_2.png"))); // NOI18N
        Reports.add(jLabel5);
        jLabel5.setBounds(10, 0, 160, 180);

        jPanel2.add(Reports, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 190, 180));

        Out.setBackground(new java.awt.Color(0, 51, 51));
        Out.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OutMouseExited(evt);
            }
        });
        Out.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/6_2.png"))); // NOI18N
        Out.add(jLabel7);
        jLabel7.setBounds(10, 0, 170, 180);

        jPanel2.add(Out, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 190, 180));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 940, 570));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, -1));

        App.setBackground(new java.awt.Color(0, 51, 51));
        App.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        App.setForeground(new java.awt.Color(255, 255, 255));
        App.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        App.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AppMouseExited(evt);
            }
        });
        App.setLayout(null);

        AppLbl.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        AppLbl.setForeground(new java.awt.Color(255, 255, 255));
        AppLbl.setText("APPLICATIONS");
        App.add(AppLbl);
        AppLbl.setBounds(85, 16, 189, 29);

        jPanel1.add(App, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 360, 60));

        Mentor.setBackground(new java.awt.Color(0, 51, 51));
        Mentor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Mentor.setForeground(new java.awt.Color(255, 255, 255));
        Mentor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Mentor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MentorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MentorMouseExited(evt);
            }
        });
        Mentor.setLayout(null);

        AssignLbl.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        AssignLbl.setForeground(new java.awt.Color(255, 255, 255));
        AssignLbl.setText("ASSIGNMENTS");
        Mentor.add(AssignLbl);
        AssignLbl.setBounds(90, 20, 190, 20);

        jPanel1.add(Mentor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 360, 60));

        User.setBackground(new java.awt.Color(0, 51, 51));
        User.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        User.setForeground(new java.awt.Color(255, 255, 255));
        User.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UserMouseExited(evt);
            }
        });
        User.setLayout(null);

        UsersLbl.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        UsersLbl.setForeground(new java.awt.Color(255, 255, 255));
        UsersLbl.setText("USERS");
        User.add(UsersLbl);
        UsersLbl.setBounds(134, 16, 86, 29);

        jPanel1.add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 360, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void setColor(JPanel p){
        p.setBackground(new Color(0,51,51));
    }
    public void resetColor(JPanel p2){
        p2.setBackground(new Color(16,79,79));
    }
    private void LogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoMouseClicked
        LandingPage Logo = new LandingPage();
        Logo.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoMouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        AdminDashboard Users = new AdminDashboard();
        Users.setVisible(true);
        dispose();
    }//GEN-LAST:event_HomeMouseClicked

    private void HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseEntered
        resetColor(Home);
    }//GEN-LAST:event_HomeMouseEntered

    private void HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseExited
        setColor(Home);
    }//GEN-LAST:event_HomeMouseExited

    private void AccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccMouseEntered
        resetColor(Acc);
    }//GEN-LAST:event_AccMouseEntered

    private void AccMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccMouseExited
        setColor(Acc);
    }//GEN-LAST:event_AccMouseExited

    private void LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseEntered
        resetColor(Logout);
    }//GEN-LAST:event_LogoutMouseEntered

    private void LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseExited
        setColor(Logout);
    }//GEN-LAST:event_LogoutMouseExited

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        session.getInstance().clearSession();
        JOptionPane.showMessageDialog(null, "Logged out successfully!");
        new LoginPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutMouseClicked

    private void AppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppMouseEntered
        resetColor(App);
    }//GEN-LAST:event_AppMouseEntered

    private void AppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppMouseExited
        setColor(App);
    }//GEN-LAST:event_AppMouseExited

    private void MentorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MentorMouseEntered
        resetColor(Mentor);
    }//GEN-LAST:event_MentorMouseEntered

    private void MentorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MentorMouseExited
        setColor(Mentor);
    }//GEN-LAST:event_MentorMouseExited

    private void UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserMouseClicked
        Users User = new Users();
        User.setVisible(true);
        dispose();
    }//GEN-LAST:event_UserMouseClicked

    private void UserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserMouseEntered
        resetColor(User);
    }//GEN-LAST:event_UserMouseEntered

    private void UserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserMouseExited
        setColor(User);
    }//GEN-LAST:event_UserMouseExited

    private void EditlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditlblMouseClicked
     EditProfile Edit = new EditProfile();
        Edit.setVisible(true);
        dispose();
    }//GEN-LAST:event_EditlblMouseClicked

    private void EditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditMouseClicked
        EditProfile Edit = new EditProfile();
        Edit.setVisible(true);
        dispose();
    }//GEN-LAST:event_EditMouseClicked

    private void EditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditMouseEntered
        resetColor(Edit);
    }//GEN-LAST:event_EditMouseEntered

    private void EditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditMouseExited
        setColor(Edit);
    }//GEN-LAST:event_EditMouseExited

    private void ReportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportsMouseEntered
        resetColor(Reports);
    }//GEN-LAST:event_ReportsMouseEntered

    private void ReportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportsMouseExited
        setColor(Reports);
    }//GEN-LAST:event_ReportsMouseExited

    private void OutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OutMouseEntered
        resetColor(Out);
    }//GEN-LAST:event_OutMouseEntered

    private void OutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OutMouseExited
        setColor(Out);
    }//GEN-LAST:event_OutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Acc;
    private javax.swing.JLabel AccLbl;
    private javax.swing.JPanel App;
    private javax.swing.JLabel AppLbl;
    private javax.swing.JLabel AssignLbl;
    private javax.swing.JPanel Edit;
    private javax.swing.JLabel Editlbl;
    private javax.swing.JLabel EmailLbl;
    private javax.swing.JLabel Emaillbl;
    private javax.swing.JPanel Home;
    private javax.swing.JLabel Idlbl;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel Logout;
    private javax.swing.JPanel Mentor;
    private javax.swing.JLabel NameLbl;
    private javax.swing.JLabel Namelbl;
    private javax.swing.JPanel Out;
    private javax.swing.JLabel Pics;
    private javax.swing.JPanel Reports;
    private javax.swing.JLabel TypeLbl;
    private javax.swing.JLabel Typelbl;
    private javax.swing.JPanel User;
    private javax.swing.JLabel Usernm;
    private javax.swing.JLabel UsersLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
