/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Config.config;
import Config.session;
import Main.LandingPage;
import Main.LoginPage;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sheena
 */
public class Users extends javax.swing.JFrame {

    /**
     * Creates new form Users
     */
    session sess = session.getInstance();
    public Users() {
        if (session.isInstanceEmpty() || sess.getUserId() == 0) {
            JOptionPane.showMessageDialog(null, "Login Required!");
            new LoginPage().setVisible(true);
            dispose();
            return;
        }        
        initComponents();
        DisplayUser();
        
        this.addWindowFocusListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowGainedFocus(java.awt.event.WindowEvent e) {
            DisplayUser();
        }
    });
    }
    
    void DisplayUser(){
    
        config con = new config();
        String sql = "SELECT * FROM tbl_accts";
        con.displayData(sql, UserTable);
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        UsersPage = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        Home = new javax.swing.JPanel();
        HomeLbl = new javax.swing.JLabel();
        App = new javax.swing.JPanel();
        AppLbl = new javax.swing.JLabel();
        Users = new javax.swing.JPanel();
        UsersLbl = new javax.swing.JLabel();
        Mentors = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Acc = new javax.swing.JPanel();
        AccLbl = new javax.swing.JLabel();
        Logout = new javax.swing.JPanel();
        LogoutLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Add = new javax.swing.JPanel();
        AddLbl = new javax.swing.JLabel();
        Update = new javax.swing.JPanel();
        UpdateLbl = new javax.swing.JLabel();
        Delete = new javax.swing.JPanel();
        DeleteLbl = new javax.swing.JLabel();
        Search = new javax.swing.JPanel();
        SearchLbl = new javax.swing.JLabel();
        SearchText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        UserTable = new javax.swing.JTable();
        Bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1300, 737));
        setMinimumSize(new java.awt.Dimension(1300, 737));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        jPanel1.setMaximumSize(new java.awt.Dimension(1300, 737));
        jPanel1.setMinimumSize(new java.awt.Dimension(1300, 737));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 737));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        Logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoMouseClicked(evt);
            }
        });
        jPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 40, 290, 110));

        UsersPage.setFont(new java.awt.Font("Bookman Old Style", 1, 48)); // NOI18N
        UsersPage.setForeground(new java.awt.Color(255, 255, 255));
        UsersPage.setText("USERS");
        jPanel1.add(UsersPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, -1, -1));

        Title.setFont(new java.awt.Font("Broadway", 2, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("EnergiFy");
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 180, 30));

        Home.setBackground(new java.awt.Color(0, 51, 51));
        Home.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeMouseExited(evt);
            }
        });
        Home.setLayout(null);

        HomeLbl.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        HomeLbl.setForeground(new java.awt.Color(255, 255, 255));
        HomeLbl.setText("HOME");
        Home.add(HomeLbl);
        HomeLbl.setBounds(139, 16, 79, 29);

        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 360, 60));

        App.setBackground(new java.awt.Color(0, 51, 51));
        App.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        App.setForeground(new java.awt.Color(255, 255, 255));
        App.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        App.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AppMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AppMouseExited(evt);
            }
        });
        App.setLayout(null);

        AppLbl.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        AppLbl.setForeground(new java.awt.Color(255, 255, 255));
        AppLbl.setText("APPLICATIONS");
        App.add(AppLbl);
        AppLbl.setBounds(85, 16, 189, 29);

        jPanel1.add(App, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 360, 60));

        Users.setBackground(new java.awt.Color(16, 79, 79));
        Users.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Users.setForeground(new java.awt.Color(255, 255, 255));
        Users.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Users.setLayout(null);

        UsersLbl.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        UsersLbl.setForeground(new java.awt.Color(255, 255, 255));
        UsersLbl.setText("USERS");
        Users.add(UsersLbl);
        UsersLbl.setBounds(134, 16, 86, 29);

        jPanel1.add(Users, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 360, 60));

        Mentors.setBackground(new java.awt.Color(0, 51, 51));
        Mentors.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Mentors.setForeground(new java.awt.Color(255, 255, 255));
        Mentors.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Mentors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MentorsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MentorsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MentorsMouseExited(evt);
            }
        });
        Mentors.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ASSIGNMENTS");
        Mentors.add(jLabel5);
        jLabel5.setBounds(90, 20, 187, 20);

        jPanel1.add(Mentors, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 360, 60));

        Acc.setBackground(new java.awt.Color(0, 51, 51));
        Acc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Acc.setForeground(new java.awt.Color(255, 255, 255));
        Acc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Acc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AccMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AccMouseExited(evt);
            }
        });
        Acc.setLayout(null);

        AccLbl.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        AccLbl.setForeground(new java.awt.Color(255, 255, 255));
        AccLbl.setText("ACCOUNT");
        Acc.add(AccLbl);
        AccLbl.setBounds(114, 16, 125, 29);

        jPanel1.add(Acc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 360, 60));

        Logout.setBackground(new java.awt.Color(0, 51, 51));
        Logout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutMouseExited(evt);
            }
        });
        Logout.setLayout(null);

        LogoutLbl.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        LogoutLbl.setForeground(new java.awt.Color(255, 255, 255));
        LogoutLbl.setText("LOGOUT");
        Logout.add(LogoutLbl);
        LogoutLbl.setBounds(126, 16, 107, 29);

        jPanel1.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 690, 360, 60));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102,90));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 51), java.awt.Color.lightGray));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Add.setBackground(new java.awt.Color(0, 51, 51));
        Add.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddMouseExited(evt);
            }
        });
        Add.setLayout(null);

        AddLbl.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        AddLbl.setForeground(new java.awt.Color(255, 255, 255));
        AddLbl.setText("ADD");
        Add.add(AddLbl);
        AddLbl.setBounds(44, 16, 41, 22);

        jPanel2.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 50));

        Update.setBackground(new java.awt.Color(0, 51, 51));
        Update.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UpdateMouseExited(evt);
            }
        });
        Update.setLayout(null);

        UpdateLbl.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        UpdateLbl.setForeground(new java.awt.Color(255, 255, 255));
        UpdateLbl.setText("UPDATE");
        Update.add(UpdateLbl);
        UpdateLbl.setBounds(27, 16, 79, 22);

        jPanel2.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 130, 50));

        Delete.setBackground(new java.awt.Color(0, 51, 51));
        Delete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeleteMouseExited(evt);
            }
        });
        Delete.setLayout(null);

        DeleteLbl.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        DeleteLbl.setForeground(new java.awt.Color(255, 255, 255));
        DeleteLbl.setText("DELETE");
        Delete.add(DeleteLbl);
        DeleteLbl.setBounds(24, 16, 81, 22);

        jPanel2.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 130, 50));

        Search.setBackground(new java.awt.Color(0, 51, 51));
        Search.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SearchMouseExited(evt);
            }
        });
        Search.setLayout(null);

        SearchLbl.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        SearchLbl.setForeground(new java.awt.Color(255, 255, 255));
        SearchLbl.setText("SEARCH");
        Search.add(SearchLbl);
        SearchLbl.setBounds(25, 16, 81, 22);

        jPanel2.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 130, 50));

        SearchText.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.lightGray));
        SearchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTextActionPerformed(evt);
            }
        });
        SearchText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SearchTextKeyTyped(evt);
            }
        });
        jPanel2.add(SearchText, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 300, 50));

        UserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(UserTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 900, 460));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 940, 570));

        Bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.png"))); // NOI18N
        jPanel1.add(Bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1310, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SearchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTextActionPerformed

    private void AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseClicked
        Add_1 Add = new Add_1();
        Add.setVisible(true);
        dispose();
    }//GEN-LAST:event_AddMouseClicked

    private void DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseClicked
        int row = UserTable.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Select a user first!");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to delete this user?",
        "Confirm Delete",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) return;

    int id = Integer.parseInt(UserTable.getValueAt(row, 0).toString());

    config conf = new config();
    String sql = "DELETE FROM tbl_accts WHERE a_id=?";

    conf.addRecord(sql, id);

    JOptionPane.showMessageDialog(this, "User deleted successfully!");
    DisplayUser();
    }//GEN-LAST:event_DeleteMouseClicked

    private void SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseClicked

    config conf = new config();

    String keyword = SearchText.getText().trim();

    if (keyword.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a name or email to search.");
        return;
    }

    String sql = "SELECT a_id, name, email, password, type, status " +
                 "FROM tbl_accts WHERE name LIKE '%" + keyword + "%' " +
                 "OR email LIKE '%" + keyword + "%'";

    conf.displayData(sql, UserTable);

    if (UserTable.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "Doesn't Exist");
        DisplayUser();
    }


    }//GEN-LAST:event_SearchMouseClicked
    public void setColor(JPanel p){
    p.setBackground(new Color(0,51,51));
    }
    public void resetColor(JPanel p){
    p.setBackground(new Color(0,102,102));
    }
    private void HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseEntered
        resetColor(Home);
    }//GEN-LAST:event_HomeMouseEntered

    private void HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseExited
        setColor(Home);
    }//GEN-LAST:event_HomeMouseExited

    private void AppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppMouseEntered
        resetColor(App);
    }//GEN-LAST:event_AppMouseEntered

    private void AppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppMouseExited
        setColor(App);
    }//GEN-LAST:event_AppMouseExited

    private void MentorsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MentorsMouseEntered
        resetColor(Mentors);
    }//GEN-LAST:event_MentorsMouseEntered

    private void MentorsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MentorsMouseExited
        setColor(Mentors);
    }//GEN-LAST:event_MentorsMouseExited

    private void AccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccMouseEntered
        resetColor(Acc);
    }//GEN-LAST:event_AccMouseEntered

    private void AccMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccMouseExited
        setColor(Acc);
    }//GEN-LAST:event_AccMouseExited

    private void LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseEntered
        resetColor(Logout);
    }//GEN-LAST:event_LogoutMouseEntered

    private void LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseExited
        setColor(Logout);
    }//GEN-LAST:event_LogoutMouseExited

    private void AddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseEntered
        resetColor(Add);
    }//GEN-LAST:event_AddMouseEntered

    private void AddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseExited
        setColor(Add);
    }//GEN-LAST:event_AddMouseExited

    private void UpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseEntered
        resetColor(Update);
    }//GEN-LAST:event_UpdateMouseEntered

    private void UpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseExited
        setColor(Update);
    }//GEN-LAST:event_UpdateMouseExited

    private void DeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseEntered
        resetColor(Delete);
    }//GEN-LAST:event_DeleteMouseEntered

    private void DeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseExited
        setColor(Delete);
    }//GEN-LAST:event_DeleteMouseExited

    private void SearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseEntered
        resetColor(Search);
    }//GEN-LAST:event_SearchMouseEntered

    private void SearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseExited
        setColor(Search);
    }//GEN-LAST:event_SearchMouseExited

    private void LogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoMouseClicked
        LandingPage Logo = new LandingPage();
        Logo.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoMouseClicked

    private void UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseClicked


    int row = UserTable.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a user to update.");
        return;
    }

    int a_id = Integer.parseInt(UserTable.getValueAt(row, 0).toString());
    String name = UserTable.getValueAt(row, 1).toString();
    String email = UserTable.getValueAt(row, 2).toString();
    String password = UserTable.getValueAt(row, 3).toString();
    String type = UserTable.getValueAt(row, 4).toString();
    String status = UserTable.getValueAt(row, 5).toString();

    Update up = new Update (a_id, name, email, password, type, status);
    up.setVisible(true);
    dispose();


    }//GEN-LAST:event_UpdateMouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        AdminDashboard Users = new AdminDashboard();
        Users.setVisible(true);
        dispose();
    }//GEN-LAST:event_HomeMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        session.getInstance().clearSession();
        JOptionPane.showMessageDialog(null, "Logged out successfully!");
        new LoginPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutMouseClicked

    private void AccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccMouseClicked
        AdminProfile Acc = new AdminProfile();
        Acc.setVisible(true);
        dispose();
    }//GEN-LAST:event_AccMouseClicked

    private void SearchTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchTextKeyTyped
        String searchText = SearchText.getText();
        String sql = "SELECT * FROM tbl_accts WHERE a_id LIKE ? or name LIKE ? or lname LIKE ? or uname LIKE ? or email LIKE ? or type LIKE ? or status LIKE ?";
        config conf = new config();
        conf.displayData(sql, UserTable,
        "%" + searchText + "%",
        "%" + searchText + "%",
        "%" + searchText + "%",
        "%" + searchText + "%",
        "%" + searchText + "%",
        "%" + searchText + "%",
        "%" + searchText + "%");
    }//GEN-LAST:event_SearchTextKeyTyped

    private void AppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppMouseClicked
       Applications App = new Applications();
        App.setVisible(true);
        dispose();
    }//GEN-LAST:event_AppMouseClicked

    private void MentorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MentorsMouseClicked
        Assignments Mentor = new Assignments();
        Mentor.setVisible(true);
        dispose();
    }//GEN-LAST:event_MentorsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Users().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Acc;
    private javax.swing.JLabel AccLbl;
    private javax.swing.JPanel Add;
    private javax.swing.JLabel AddLbl;
    private javax.swing.JPanel App;
    private javax.swing.JLabel AppLbl;
    private javax.swing.JLabel Bg;
    private javax.swing.JPanel Delete;
    private javax.swing.JLabel DeleteLbl;
    private javax.swing.JPanel Home;
    private javax.swing.JLabel HomeLbl;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel Logout;
    private javax.swing.JLabel LogoutLbl;
    private javax.swing.JPanel Mentors;
    private javax.swing.JPanel Search;
    private javax.swing.JLabel SearchLbl;
    private javax.swing.JTextField SearchText;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel Update;
    private javax.swing.JLabel UpdateLbl;
    private javax.swing.JTable UserTable;
    private javax.swing.JPanel Users;
    private javax.swing.JLabel UsersLbl;
    private javax.swing.JLabel UsersPage;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
