/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mentor;

import Admin.AdminProfile;
import Config.session;
import Main.LandingPage;
import Main.LoginPage;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.sql.PreparedStatement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sheena
 */
public class EditProfileM extends javax.swing.JFrame {

    /**
     * Creates new form EditProfileM
     */
    session sess = session.getInstance();
    public EditProfileM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Home = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Acc = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Logout = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        NameLbl = new javax.swing.JLabel();
        EmailLbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Pfp = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Idlbl = new javax.swing.JLabel();
        Edit = new javax.swing.JPanel();
        TypeLbl3 = new javax.swing.JLabel();
        Out = new javax.swing.JPanel();
        TypeLbl = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        Username = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        TypeLbl1 = new javax.swing.JLabel();
        Typelbl = new javax.swing.JLabel();
        TypeLbl2 = new javax.swing.JLabel();
        Save = new javax.swing.JPanel();
        TypeLbl4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        App = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Mentors = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1300, 737));
        setMinimumSize(new java.awt.Dimension(1300, 737));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(1300, 737));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        Logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoMouseClicked(evt);
            }
        });
        jPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 30, 290, 110));

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("EDIT PROFILE");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Broadway", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EnergiFy");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 180, 30));

        Home.setBackground(new java.awt.Color(0, 51, 51));
        Home.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeMouseExited(evt);
            }
        });
        Home.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HOME");
        Home.add(jLabel2);
        jLabel2.setBounds(139, 16, 79, 29);

        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 360, 60));

        Acc.setBackground(new java.awt.Color(0, 102, 102));
        Acc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Acc.setForeground(new java.awt.Color(255, 255, 255));
        Acc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Acc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AccMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AccMouseExited(evt);
            }
        });
        Acc.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ACCOUNT");
        Acc.add(jLabel7);
        jLabel7.setBounds(120, 20, 125, 20);

        jPanel1.add(Acc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 360, 60));

        Logout.setBackground(new java.awt.Color(0, 51, 51));
        Logout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutMouseExited(evt);
            }
        });
        Logout.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("LOGOUT");
        Logout.add(jLabel8);
        jLabel8.setBounds(126, 16, 107, 29);

        jPanel1.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 360, 60));

        jPanel2.setBackground(new java.awt.Color(16, 79, 79));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameLbl.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        NameLbl.setForeground(new java.awt.Color(255, 255, 255));
        NameLbl.setText("Name:");
        jPanel2.add(NameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));

        EmailLbl.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        EmailLbl.setForeground(new java.awt.Color(255, 255, 255));
        EmailLbl.setText("Email:");
        jPanel2.add(EmailLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, -1, 20));

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setLayout(null);

        Pfp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg (11).png"))); // NOI18N
        jPanel3.add(Pfp);
        Pfp.setBounds(50, 30, 200, 200);

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 310, 260));

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, 20));

        Idlbl.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        Idlbl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(Idlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 90, 40));

        Edit.setBackground(new java.awt.Color(0, 51, 51));
        Edit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditMouseExited(evt);
            }
        });
        Edit.setLayout(null);

        TypeLbl3.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        TypeLbl3.setForeground(new java.awt.Color(255, 255, 255));
        TypeLbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TypeLbl3.setText("SELECT");
        Edit.add(TypeLbl3);
        TypeLbl3.setBounds(50, 10, 170, 40);

        jPanel2.add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 270, 60));

        Out.setBackground(new java.awt.Color(0, 51, 51));
        Out.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OutMouseExited(evt);
            }
        });
        Out.setLayout(null);

        TypeLbl.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        TypeLbl.setForeground(new java.awt.Color(255, 255, 255));
        TypeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TypeLbl.setText("CANCEL");
        Out.add(TypeLbl);
        TypeLbl.setBounds(30, 20, 210, 40);

        jPanel2.add(Out, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 270, 80));

        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        jPanel2.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 250, 40));
        jPanel2.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 250, 40));
        jPanel2.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 250, 40));

        TypeLbl1.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        TypeLbl1.setForeground(new java.awt.Color(255, 255, 255));
        TypeLbl1.setText("Type:");
        jPanel2.add(TypeLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, -1, -1));

        Typelbl.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        Typelbl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(Typelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 220, 40));

        TypeLbl2.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        TypeLbl2.setForeground(new java.awt.Color(255, 255, 255));
        TypeLbl2.setText("Username:");
        jPanel2.add(TypeLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, -1, -1));

        Save.setBackground(new java.awt.Color(0, 51, 51));
        Save.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SaveMouseExited(evt);
            }
        });
        Save.setLayout(null);

        TypeLbl4.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        TypeLbl4.setForeground(new java.awt.Color(255, 255, 255));
        TypeLbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TypeLbl4.setText("SAVE CHANGES");
        Save.add(TypeLbl4);
        TypeLbl4.setBounds(30, 20, 210, 40);

        jPanel2.add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 270, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 940, 570));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, -1));

        App.setBackground(new java.awt.Color(0, 51, 51));
        App.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        App.setForeground(new java.awt.Color(255, 255, 255));
        App.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        App.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AppMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AppMouseExited(evt);
            }
        });
        App.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("APPLICATIONS");
        App.add(jLabel3);
        jLabel3.setBounds(90, 20, 200, 29);

        jPanel1.add(App, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 360, 60));

        Mentors.setBackground(new java.awt.Color(0, 51, 51));
        Mentors.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Mentors.setForeground(new java.awt.Color(255, 255, 255));
        Mentors.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Mentors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MentorsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MentorsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MentorsMouseExited(evt);
            }
        });
        Mentors.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CLIENT");
        Mentors.add(jLabel5);
        jLabel5.setBounds(130, 20, 100, 20);

        jPanel1.add(Mentors, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 360, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoMouseClicked
        LandingPage Logo = new LandingPage();
        Logo.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoMouseClicked
    public void setColor(JPanel p){
        p.setBackground(new Color(0,51,51));
    }
    public void resetColor(JPanel p2){
        p2.setBackground(new Color(16,79,79));
    }
    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        MentorDashboard Users = new MentorDashboard();
        Users.setVisible(true);
        dispose();
    }//GEN-LAST:event_HomeMouseClicked

    private void HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseEntered
        resetColor(Home);
    }//GEN-LAST:event_HomeMouseEntered

    private void HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseExited
        setColor(Home);
    }//GEN-LAST:event_HomeMouseExited

    private void AccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccMouseEntered
        resetColor(Acc);
    }//GEN-LAST:event_AccMouseEntered

    private void AccMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccMouseExited
        setColor(Acc);
    }//GEN-LAST:event_AccMouseExited

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        session.getInstance().clearSession();
        JOptionPane.showMessageDialog(null, "Logged out successfully!");
        new LoginPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutMouseClicked

    private void LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseEntered
        resetColor(Logout);
    }//GEN-LAST:event_LogoutMouseEntered

    private void LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseExited
        setColor(Logout);
    }//GEN-LAST:event_LogoutMouseExited

    private void EditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String imagePath = selectedFile.getAbsolutePath();

            try (java.sql.Connection con = Config.config.connectDB();
                PreparedStatement pst = con.prepareStatement(
                    "UPDATE tbl_accts SET image=? WHERE a_id=?")) {

                pst.setString(1, imagePath);
                pst.setInt(2, sess.getUserId());
                pst.executeUpdate();

                ImageIcon icon = new ImageIcon(imagePath);
                Image img = icon.getImage().getScaledInstance(
                    Pfp.getWidth(),
                    Pfp.getHeight(),
                    Image.SCALE_SMOOTH
                );
                Pfp.setIcon(new ImageIcon(img));

                JOptionPane.showMessageDialog(this, "Profile picture updated!");

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_EditMouseClicked

    private void EditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditMouseEntered
        resetColor(Edit);
    }//GEN-LAST:event_EditMouseEntered

    private void EditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditMouseExited
        setColor(Edit);
    }//GEN-LAST:event_EditMouseExited

    private void OutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OutMouseClicked
        new ProfileM().setVisible(true);
        dispose();
    }//GEN-LAST:event_OutMouseClicked

    private void OutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OutMouseEntered
        resetColor(Out);
    }//GEN-LAST:event_OutMouseEntered

    private void OutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OutMouseExited
        setColor(Out);
    }//GEN-LAST:event_OutMouseExited

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void SaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveMouseClicked
        String newName = Name.getText();
        String newEmail = Email.getText();
        String newUsername = Username.getText();

        if (newName.isEmpty() || newEmail.isEmpty() || newUsername.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to save changes?",
            "Confirm Save",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            java.sql.Connection con = Config.config.connectDB();
            String sql = "UPDATE tbl_accts SET name=?, email=?, uname=? WHERE a_id=?";
            PreparedStatement pst = con.prepareStatement(sql);

            pst.setString(1, newName);
            pst.setString(2, newEmail);
            pst.setString(3, newUsername);
            pst.setInt(4, sess.getUserId());

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Profile updated successfully!");

            pst.close();
            con.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }

        new AdminProfile().setVisible(true);
        dispose();
    }//GEN-LAST:event_SaveMouseClicked

    private void SaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveMouseEntered
        resetColor(Save);
    }//GEN-LAST:event_SaveMouseEntered

    private void SaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveMouseExited
        setColor(Save);
    }//GEN-LAST:event_SaveMouseExited

    private void AppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppMouseClicked
        ApplicationsM App = new ApplicationsM();
        App.setVisible(true);
        dispose();
    }//GEN-LAST:event_AppMouseClicked

    private void AppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppMouseEntered
        resetColor(App);
    }//GEN-LAST:event_AppMouseEntered

    private void AppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppMouseExited
        setColor(App);
    }//GEN-LAST:event_AppMouseExited

    private void MentorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MentorsMouseClicked
        User Mentors = new User();
        Mentors.setVisible(true);
        dispose();
    }//GEN-LAST:event_MentorsMouseClicked

    private void MentorsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MentorsMouseEntered
        resetColor(Mentors);
    }//GEN-LAST:event_MentorsMouseEntered

    private void MentorsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MentorsMouseExited
        setColor(Mentors);
    }//GEN-LAST:event_MentorsMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProfileM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProfileM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProfileM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProfileM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditProfileM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Acc;
    private javax.swing.JPanel App;
    private javax.swing.JPanel Edit;
    private javax.swing.JTextField Email;
    private javax.swing.JLabel EmailLbl;
    private javax.swing.JPanel Home;
    private javax.swing.JLabel Idlbl;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel Logout;
    private javax.swing.JPanel Mentors;
    private javax.swing.JTextField Name;
    private javax.swing.JLabel NameLbl;
    private javax.swing.JPanel Out;
    private javax.swing.JLabel Pfp;
    private javax.swing.JPanel Save;
    private javax.swing.JLabel TypeLbl;
    private javax.swing.JLabel TypeLbl1;
    private javax.swing.JLabel TypeLbl2;
    private javax.swing.JLabel TypeLbl3;
    private javax.swing.JLabel TypeLbl4;
    private javax.swing.JLabel Typelbl;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
